<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AppSOA/soaproyect/getMailsSV" name="getMailsSV-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AppSOA/soaproyect/getMailsSV" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AppSOA/soaproyect/getMailsSV" location="../getMailsSV.wsdl"/>
  <binding name="getMailsSV_ptt-binding" type="tns:getMailsSV_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="getMailsSV">
      <soap:operation soapAction="getMailsSV"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="getMailsSV-service">
    <port name="getMailsSV-port" binding="tns:getMailsSV_ptt-binding">
      <soap:address location="jca://eis/DB/EscuelaSOA2Con"/>
    </port>
  </service>
</definitions>